font_family      JetBrainsMono Nerd Font
bold_font         auto
italic_font       auto
bold_italic_font  auto
font_size         12.0

foreground #dcd7ba
background #1f1f28
selection_foreground #1f1f28
selection_background #dcd7ba

cursor #dcd7ba
cursor_text_color #1f1f28

url_color #7e9cd8

# black
color0 #090909
color8 #54546d

# red
color1 #c34043
color9 #d96b6c

# green
color10 #779b74
color2 #76946a

# yellow
color11 #dca06b
color3 #dca561

# blue
color12 #7fb4ca
color4 #7e9cd8

# magenta
color13 #8a7fad
color5 #957fb8

# cyan
color14 #86b4c1
color6 #6bb1b4

# white
color15 #dcd7ba
color7 #c0b89c

shell_integration enabled

map ctrl+shift+up     scroll_line_up
map ctrl+shift+down   scroll_line_down
map ctrl+shift+k      scroll_line_up
map ctrl+shift+j      scroll_line_down
map ctrl+shift+home   scroll_home
map ctrl+shift+end    scroll_end

map ctrl+shift+equal  change_font_size all +2.0
map ctrl+shift+minus  change_font_size all -2.0
map ctrl+shift+0      change_font_size all 0

active_border_color #7e9cd8
inactive_border_color #54546d

tab_bar_style powerline
tab_bar_edge top
active_tab_foreground #1f1f28
active_tab_background #7e9cd8
inactive_tab_foreground #dcd7ba
inactive_tab_background #2a2a37

background_opacity 0.95
